name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  update-and-validate:
    name: Update, Validate, Lint, and Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
      - name: Install jq
        run: sudo apt-get install jq
      - name: Bump Version
        run: |
          APP_VERSION=$(jq -r .version .homeycompose/app.json)
          jq ".version=\"$APP_VERSION\"" package.json > package.json.tmp
          mv package.json.tmp package.json
      - name: Check Dependency Updates
        run: |
          npm install -g npm-check-updates
          npx ncu -u
      - name: Install Dependencies
        run: npm install
      - name: Set Up
        run: |
          echo '{}' > app.json
          mkdir locales
      - name: Validate App # Compile TypeScript
        run: |
          npm install -g homey
          npx homey app validate --level publish
      - name: Clean Up
        run: |
          rm app.json
          rm -rf locales
      - name: Lint and Fix Errors
        run: npm run lint:fix
      - name: Format Code
        run: npm run format:fix
      - name: Commit Changes
        run: |
          git config --local user.name 'GitHub Actions'
          git config --local user.email 'actions@github.com'
          git add -A
          if ! git diff --cached --exit-code; then
            git commit -m "Automated changes"
            if [[ "${{ github.ref }}" == 'refs/heads/main' ]]; then
              sudo apt-get update
              sudo apt-get install gh
              echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
              BRANCH_NAME="automated-updates-$(date +'%Y%m%d%H%M%S')"
              git checkout -b $BRANCH_NAME
              git push origin $BRANCH_NAME
              gh pr create --base main --head $BRANCH_NAME --title "Automated PR" --body "This is an automated PR."
            else
              git pull origin ${{ github.head_ref }} --rebase
              git push origin HEAD:${{ github.head_ref }}
            fi
          else
            echo "No changes to commit."
          fi

  sonarcloud:
    name: SonarCloud
    needs: [update-and-validate]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Dependencies
        run: npm install
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
