name: Translate app
on:
  workflow_dispatch:

jobs:
  main:
    name: Translate app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: https://npm.pkg.github.com
          scope: '@olivierzal'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Translate app
        uses: athombv/github-action-homey-app-translate@master
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
      - name: Commit, push & create PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git config --local user.email "sysadmin+githubactions@athom.com"
          git config --local user.name "Homey Github Actions Bot"

          git checkout -b feature/openai-translations

          git add -A
          git commit -m "Automatic translations with OpenAI"
          git push --set-upstream origin feature/openai-translations

          gh pr create --fill
